default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= Rails.application.credentials[:USER_DB] %>
  password: <%= Rails.application.credentials[:PASS_DB] %>
  database: navedex_api_development

test:
  <<: *default
  username: <%= Rails.application.credentials[:USER_DB] %>
  password: <%= Rails.application.credentials[:PASS_DB] %>
  database: navedex_api_test

production:
  <<: *default
  database: navedex_api_production
  username: navedex_api
  password: <%= ENV['NAVEDEX_API_DATABASE_PASSWORD'] %>
